### PR TITLE
fix(cargo-codspeed): fix build when package is included in its deps

### LINKED ISSUE #37: `cargo codspeed build` doesn't build virtual manifest
I'm trying to integrate CodSpeed into [this](https://github.com/tversteeg/blit) repo which contains a virtual manifest. So the `Cargo.toml` contains a `[workspace]` section but the main package is not included in it.

When I run `cargo codspeed build` I get the following output:

```
   Collected 1 benchmark suite(s) to build
    Building benchmarks
       Error There are multiple `blit` packages in your project, and the specification `blit` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  file:///.../blit#0.8.5
  https://github.com/rust-lang/crates.io-index#blit@0.8.5
```

There's no way to select the main package, which should be selected by default anyway.

### PR DESCRIPTION
**Pull request by adriencaccia**
Fix #37

### CODE REVIEW

File: crates/cargo-codspeed/src/build.rs [hunk 1]
```diff
@@ -51,14 +56,17 @@ pub fn build_benches(
...
+    let (package, is_root) = match package_name.as_ref() {
+        Some(package_name) => (
+            ws.members()
+                .find(|p| p.name().to_string() == *package_name)
+                .ok_or_else(|| anyhow!("Package {} not found", package_name))?,
+            false,
+        ),
+        None => {
+            (ws.current().map_err(|_| anyhow!("No package found. If working with a workspace please use the -p option to specify a member."))?, true)
+        }
```
Comment (art049) [inline crates/cargo-codspeed/src/build.rs:68]: I think 
```
let is_root = package.is_some();
let package = if is_root {
    ...
} else {
    ...
};
```
Would be easier to read

File: crates/cargo-codspeed/src/build.rs [hunk 2]
```diff
@@ -51,14 +56,17 @@ pub fn build_benches(
...
     };
```
Comment (art049) [inline crates/cargo-codspeed/src/build.rs:69]: I think 
```rust
let is_root = package.is_none();
let package = if is_root {
    ...
} else {
    ...
};
```
Would be easier to read

File: crates/cargo-codspeed/src/build.rs [hunk 3]
```diff
@@ -18,9 +18,14 @@ fn get_compile_options(
     features: &Option<Vec<String>>,
     package: &Package,
     benches: Vec<&str>,
+    is_root: bool,
```
Comment (art049) [inline crates/cargo-codspeed/src/build.rs:21]:
```suggestion
    is_root_package: bool,
```
This would be more obvious

File: rust-toolchain.toml [hunk 4]
```diff
@@ -1,2 +1,2 @@
 [toolchain]
-channel = "1.74.0"
+channel = "1.75.0"
```
Comment (art049) [inline rust-toolchain.toml:2]: let's put this in a separate PR to isolate perf changes

**Review by art049 — APPROVED** [review]
